### ISSUE TITLE
How to get the private repository?

### ISSUE THREAD

**Issue by AnranXu** [PBA-2021S/pba#1]
Just took a look at the [submit.md](https://github.com/PBA-2021S/pba/blob/main/doc/submit.md), it says that each student will work on a private repository named  `pba-<username>`. Is it available now? Thank you.

**Comment by nobuyuki83** [comment]
Thanks for your question. It might be not very clear from the [submit.md](doc/submit.md), but I will show you how to create the repository using GitHub Classroom in the next class. Please don't miss it!  

> Using the system called "GitHub Classroom", students make their own private repository that is a copy of "https://github.com/PBA-2021S/pba" ...  In the second class, It will be shown how to make your own class repository using GitHub classroom.
